### ISSUE TITLE
Giving the table option breaks pmatrix

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#16]
The table option to revtex in https://arxiv.org/abs/1607.01291 breaks {quantumarticle}.

**Comment by cgogolin** [comment]
Here is a minimal example demonstrating the problem:

```
\documentclass[table]{quantumarticle}
\usepackage{amsmath}

\begin{document}

\title{a}

\author{b}

\begin{abstract}
  c
\end{abstract}
\maketitle

\begin{align}
  \begin{pmatrix}
    a & b
\end{pmatrix}
\end{align}

\end{document}
```

equation instead of align works equally well.

**Comment by cgranade** [comment]
This is a quite odd one, not the least of which because there's no `\DeclareOption{table}` in either `quantumarticle.cls` or `revtex4-1.cls` that would seem to be sensitive to `[table]`. Indeed, I didn't find documentation for that option in the RevTeX manual.  To test, I added the following debugging code to `quantumarticle.cls` to handle unknown options, as suggested [on Wikibooks](https://en.wikibooks.org/wiki/LaTeX/Creating_Packages):

```
\DeclareOption*{
  \ClassWarning{myclass}{Unknown option '\CurrentOption'}
}
```

When used with `[table]`, this correctly raised a warning, but didn't prevent the error. I'll look a bit more into this.

**Comment by cgogolin** [comment]
Options in the documentclass are passed on to packages regardless of whether they are unknown to the class or not. I however also did not find any table option in amsmath and it doesn't seem to load any other packages. A a puzzled...

**Comment by cgranade** [comment]
Right, agreed. I guess I was mainly confused because that leaves us with very little information about what part of the class might somehow be sensitive to the presence of that option. Trying with other undefined options didn't reproduce the error.

**Comment by cgogolin** [comment]
I have now added code that makes `quantumarticle` throw an erro if the `table` options if given. This way at least users get a meaningful error message and are told what to do to resolve the problem.

**Comment by cgranade** [comment]
Seems like a very reasonable solution for now. I am curious what internal
commands were sensitive to `[table]`, but I agree that it's important to
make sure there's a meaningful error message first and foremost.

**Comment by dbranford** [comment]
Using the example given in https://github.com/cgogolin/quantum-journal/issues/16#issuecomment-255056351 I receive the class error as to be expected from https://github.com/cgogolin/quantum-journal/blob/5d8fc2b9192d87caf6aed6cc1715e61ca1d2dfea/quantumarticle.cls#L163 however removing `\ClassError{quantumarticle}{... }`  from `\DeclareOption{table}{...}` or removing `\DeclareOption{table}{...}` altogether I receive no further error with `quantumarticle 2017/01/23` (but do generate an `! Undefined control sequence. <recently read> \the@toks` error with the same example using `quantumarticle 2016/08/23`) from both an up-to-date MiKTeX and TeXLive 2015.

**Comment by cgogolin** [comment]
Yes, this is intended behavior. We precisely added this `ClassError` to not leave people with this strange undefined control sequence error, but show them a way to solve the problem. The class `table` option doesn't have any effect, except from causing this error, and I don't understand how it actually causes this error.
If you have any insight into what is the root cause of this error please let us know so that we can work on a proper fix. Thanks for reporting!

**Comment by dbranford** [comment]
With `2016/08/23` I get the `! Undefined control sequence. <recently read> \the@toks` error, but with `2017/01/23` the error no longer appears.  In `2017/01/23` I cannot replicate the underlying error which caused you to add the `ClassError` - it seems that intermediate changes may have inadvertently fixed or reduced the scope of the original error which this issue describes and now the `table` option only produces an error because the `ClassError` you added remains.

**Comment by cgogolin** [comment]
Ah, so sorry. I misunderstood your comment. Apologies. I will test this and potentially remove the ClassError in case everything works. Thanks!!!

**Comment by cgogolin** [comment]
This problem solved itself when we moved all option processing to `xkeyval` in 1e1e0c74a984f5cfd2245f88a7275c9561fbbd5f .
