### ISSUE TITLE
File `ltxgrid.sty' not found

### ISSUE THREAD

**Issue by Strilanc** [cgogolin/quantum-journal#36]
After I ran the install instructions and attempted to build an article, I got a dependency error:

```
File `ltxgrid.sty' not found.
```

Install instructions should include any steps needed to get dependencies working. You should test them on Ubuntu running from a Live CD to be sure to meet this criteria.

(I *guess* you can assume that at least git and latex have been installed. But I consider even that to be pushing it.)

**Comment by cgogolin** [comment]
Thanks for your report!
Well, git is not in any way necessary to use quantumarticle.cls and that the file is useless without LaTeX should be obvious from the title "LaTeX document class for Quantum"...
Anyway, you are right about `ltxgrid.sty`. It is not entirely trivial how to get it as it is usually distributed along with the revtex package in packages such as `texlive-publishers`, in the case of texlive. I presumed that  everyone has that installed anyway because it provides the style files of several major publishers.
I will update the documentation shortly and add a section on dependencies.
