### ISSUE TITLE
Problem with verbatim over page breaks and tikz

### ISSUE THREAD

**Issue by cgogolin** [cgogolin/quantum-journal#43]
When a `verbatim` environment goes over a page break and there is some `tikz` code in the footline (such as when the `accepted=YYYY-MM-DD` option is given) then somehow `verbatim` and `tikz` interfere, producing the following error:
```
ERROR: Package tikz Error: Sorry, some package has redefined the meaning of the math-mode dollar sign. This is incompatible with tikz and its calc library and might cause unrecoverable errors.
```
A minimal example that demonstrates this problem is the following:
```
\documentclass[accepted=2017-05-09]{quantumarticle}
\usepackage{lipsum}
\begin{document}
\lipsum[1-8]
\begin{verbatim}
a
b
c
d
e
f
g
h
i
j
\end{verbatim}
\lipsum[9-11]
\end{document}
```
(Thanks to Joe Renes for finding this)

**Comment by dbranford** [comment]
That seems to be a good fix, although perhaps using one too many `\if`s

````latex
\newsavebox\@quantumacceptedbox
\savebox\@quantumacceptedbox{\ifaccepted%
\textcolor{quantumviolet}{ \sffamily\footnotesize Accepted in {\normalsize\Quantum}\ifcsdef{@accepteddate}{ \@accepteddate}{}, click title to verify}%
\fi}
````
seems just as good, allowing 

````latex
\fancyfoot[L]{\usebox{\@quantumacceptedbox}}
````
rather than
````latex
\ifaccepted
\fancyfoot[L]{\usebox{\@quantumacceptedbox}}
\ifcsdef{@accepteddate}{ \@accepteddate}{}, click title to verify}}
\else
\fancyfoot[L]{}
\fi
````

**Comment by cgogolin** [comment]
I fear I don't understand which exact change you are suggesting...

**Comment by dbranford** [comment]
Rather than create the box if `accepted` is true, and using the box if `accepted` is true, create the box and use it independent of the state of the `accepted` switch, but make the box empty if `accepted` is false.

That way the code would only branch within the creation of the savebox, rather than branching both when deciding whether to make the box and when setting the footnote - it's just a different way of achieving the same end result but makes things slightly tidier to me (and might be better for implementing something like you suggest in https://github.com/quantum-journal/quantum-journal/issues/37#issuecomment-316057965 for example).

**Comment by cgogolin** [comment]
Mh... Creating an empty box is also not really elegant. If we go for footline note for the `unpublished` option, the I agree, that this would be better. Let's see what the outcome of the discussion in #37 is and then decide.

**Comment by cgogolin** [comment]
The way the discussion on #37 ended I tend to leave the implementation of this as is.
