### ISSUE TITLE
Revised pdfoutput error handling

### ISSUE THREAD

**Issue by johannesjmeyer** [cgogolin/quantum-journal#75]
I was just thinking about the `\pdfoutput` and the surrounding error handling. I had the idea to introduce the following code into the documentclass

```latex
\ifcsdef{pdfoutput}
{
    % Force the user to set \pdfoutput=1 after \documentclass
    \iftoggle{@nopdfoutputerror}
    {}
    {\pdfoutput=0}
}{}	
```

The reason is the following: in my LaTeX editor (TeXStudio), `\pdfoutput` has already the value 1 if I compile with PdfLaTeX. This means the pdfoutput error is never raised even if I do not include `\pdfoutput=1` in the document. With the above snippet, `\pdfoutput` would be actively disabled in the class file so that the user forcibly has to reset it to 1.

Do you think there are any dangers to this approach? Like packages that are included in the documentclass and that access `\pdfoutput`?

**Comment by cgogolin** [comment]
Good observation. Let me paraphrase to make sure I understand:

You say that if you compile with `pdflatex`, then `\pdfoutput` is already 1 and the error is never raised. If you then upload to the arXiv and don't, e.g., have a pdf figure or similar, then the arXiv will likely not produce a pdf and we have a problem. Therefore you want to raise an error even if `\pdfoutput` is 1, set it to 0 in the document class, and throw an error if it is still 0 AtBeginDocument to force them to manually set it to 1 after `\documentclass`.

Your Idea is good, but I have no idea about possible side effects of your trick and am thus wary of implementing it. Packages like hyperref and pstricks depend on the value of `\pdfoutput`.

It is quite annoying that `\pdfoutput` is not really documented anywhere. Overleaf has [this](https://www.overleaf.com/learn/latex/%5Cpdfoutput) page and there are [a few](https://tex.stackexchange.com/questions/349/what-is-the-practical-difference-between-latex-and-pdflatex/357) threads on [stackexchange](https://tex.stackexchange.com/questions/109995/pdfoutput-1-cant-replace-pdflatex-for-auto-pst-pdf). But apart from this the `\pdfoutput` option seems to be an arxiv specific quirk.

In all cases where we can reasonably avoid throwing an error only once a manuscript is typset by the arXiv we should do it, because it is frustrating to get an error at this stage and because it is really quite difficult to spot the error in the output generated by the arXiv.

Here, however, I think it is fine if the error only shows up during submission to the arXiv. It will right? If you have always used pdflatex locally and never put the option `\pdfouput=1` in the file and then upload it, the arXiv will typeset it with plain `latex` and the error will be triggered, along with a useful error message.

**Comment by johannesjmeyer** [comment]
> Good observation. Let me paraphrase to make sure I understand:
> 
> You say that if you compile with `pdflatex`, then `\pdfoutput` is already 1 and the error is never raised. If you then upload to the arXiv and don't, e.g., have a pdf figure or similar, then the arXiv will likely not produce a pdf and we have a problem. 

Exactly.

> Therefore you want to raise an error even if `\pdfoutput` is 1, set it to 0 in the document class, and throw an error if it is still 0 AtBeginDocument to force them to manually set it to 1 after `\documentclass`.

Also yes.

> Your Idea is good, but I have no idea about possible side effects of your trick and am thus wary of implementing it. Packages like hyperref and pstricks depend on the value of `\pdfoutput`.

My reasoning was that everything should still work fine if we set `\pdfoutput=0` _at the very end_ of `quantumarticle.cls`: 

- User sets `\pdfoutput=1` directly after the `\documentclass` command: no package should ever see another value than `\pdfoutput=1`, shouldn't it?
- User _doesn't_ set `\pdfoutput=1` in the document: in this case we should always throw an error, except if `nopdfoutputerror` is given. In this case we also don't care if we screw up other packages the user loads because the document won't compile anyways.
- User sets `\pdfoutput=1` but after loading packages: In this case, the aforementioned approach will likely screw with the packages. I don't see a remedy for this, because there are no other hooks we could attach the errr to than `AtBeginDocument`. Still, this is unwanted behaviour, as the author should set `\pdfoutput=1` in the first lines of the file.

> Here, however, I think it is fine if the error only shows up during submission to the arXiv. It will right? If you have always used pdflatex locally and never put the option `\pdfouput=1` in the file and then upload it, the arXiv will typeset it with plain `latex` and the error will be triggered, along with a useful error message.

I honestly don't know how an arXiv submission works, I have never submitted anything to the arXiv. But with the approach outlined above, the error will _also_ show up if pdflatex is used and `\pdfouput=1` is omitted (which is a thing we want, isn't it?)

**Comment by cgogolin** [comment]
I have an idea: We are anyway already patching `\usepackage` (see around line 260). We can throw the error there if `\pdfoutput` is not 1 and set, as you propose, `\pdfoutput=0` in the end of the class file unless `nopdfoutputerror` is given. This forces the user to put `\pdfoutput=1` before the first `\usepackage`.

Would that solve all issues?

**Comment by johannesjmeyer** [comment]
That is a very smart solution!
