### ISSUE TITLE
Use different title color and no href when documentclass doesn't include an "accepted" attribute

### ISSUE THREAD

**Issue by Strilanc** [cgogolin/quantum-journal#80]
One of the minor issues with writing a paper with Quantum in mind is that the quantumarticle.cls document class is too strongly associated with the idea that the article is submitted to or accepted by quantum.

This could be fixed by having the document class' style change behavior in small ways based on the presence or absence of the "accepted" attribute used when specifying the document class. If the latex source doesn't specify accepted, then the produced pdf should not attempt to justify itself as a Quantum paper. In fact it should try to distinguish itself from that concept, and just look like a normal paper that happens to have a stylistic similarity.

The easiest way to achieve this, I think, would be to have the title be a different color (e.g. blue instead of purple) and to remove the hyperlink from the title to a search on Quantum's site.

**Comment by johannesjmeyer** [comment]
If I understand you correctly, the feature you're missing already exists: the documentclass supports the option `unpublished` which is intended for works that are not yet accepted in quantum. Setting `unpublished` will give the behaviour you're hinting at.

We are currently in the process of adding an option `noarxiv` which is intended for authors that do not intend to use the template to submit to quantum but just because they like it. If you want to try this feature I suggest you pull the newest version of `quantumarticle.cls` from the _develop_ branch.

**Comment by Strilanc** [comment]
I think my suggestion is for `noarxiv` to be the default behavior when nothing is specified.

Although I have to say that `noarxiv` is a completely terrible name for the functionality you described. Just picture a person explaining "I just want to put it on the arxiv, I don't want to publish it in a journal" followed by the answer "Oh, if you only want to put it on the arxiv you use the noarxiv option"... it's quite funny.

You should call it `arxiv` or `preprint`.

**Comment by johannesjmeyer** [comment]
I didn't explain this in sufficient detail:

The template contains some functionalities that ensure that submitting to the arxiv works well: for example, in the vanilla template, there is an error if you use `\date{\today}` because if the paper gets recompiled by the arxiv at a later time the `\date` would change. There is also an error if the user does not specify `\pdfoutput=1`, because if this is not specified, the arxiv will not use pdfLatex. Long story short: The vanilla template limits your freedom in using it due to some arxiv quirks.
The option `noarxiv` is just deactivating all those checks _and_ sets the option `unpublished` because submitting to the arxiv is necessary if you submit to quantum.

In your case you still would probably want those checks in place, so using `unpublished` is the way to go.

**Comment by cgogolin** [comment]
Thank you for reaching out! The way you describe things, I think the `unpublished` option is what you want. We will also explain these options more prominently in the template file to make their use more obvious.
